Traceback (most recent call last):
  File "/home/vljchr004/msc-hpc/cnn_python/cnn_1.py", line 64, in <module>
    electrons_x = x[elec,:,:]
IndexError: index 144661 is out of bounds for axis 0 with size 144643
